### ISSUE TITLE
AWWWWeeEESOME

### ISSUE THREAD

**Issue by Shelly7w7** [JustTalDevelops/pizzaplug#1]
this is freaking awesome ! 😁😁😁😘😘😘😘👌👌👌👌👌

**Comment by Vecnavium** [comment]
OMG ITS SHELLY

**Comment by Vecnavium** [comment]
Its THE Shelly Omg omg omg HI!

**Comment by Vecnavium** [comment]
YOU SURE ARE RIGHT THIS IS AWESOME
YESSSSSIRRRRRRRRRR

**Comment by Vecnavium** [comment]
Damn i cant believe im talking to THE shelly7w7 omg omg

**Comment by Vecnavium** [comment]
And JustTal the penguin! But no longer. But. No. Yes. okay.

**Comment by Vecnavium** [comment]
Now I am done, FAREWELLLLLLL

ALSO FTHIS IS FREAKING AWESOME THE PLUGIN PZIZZAAAAA

**Comment by Shelly7w7** [comment]
my emails rlly scared me 🙄🙄

**Comment by Vecnavium** [comment]
ohno im sorry Shelly

**Comment by Vecnavium** [comment]
Here let me give you some love that was given to me from JustTal since the penguin has passed away and said give Shelly the love from me in case the horse(Shelly) gets scared

**Comment by Vecnavium** [comment]
Love From JustTal: HEART HEART HEART HEART HEART HEART HEART HEART!! now stfu. - justtal

**Comment by Vecnavium** [comment]
now that my job here is done. IM DONE BYEEEE

**Comment by ethaniccc** [comment]
Cool but @JustTalDevelops, but where is my free pizza!?!?!
